id: PC5854F18
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA27500
  instance_id: http://purl.bdrc.io/resource/IE27500
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - གནས་ལུགས་རང་བྱུང་གི་རྒྱུད་རྡོ་རྗེའི་སྙིང་པོ།
  alt_title:
    en-x-mixed:
    - Dag snaṅ ye śes drwa ba las Gnas lugs raṅ byuṅ gi rgyud rdo rjeʼi sñiṅ po bźugs
      so /Khrag-thuṅ Bdud-joms-rdo-rjes gsuṅs.
    zh-latn-pinyin-x-ndia:
    - jin gang xin yao bi lu
  author: http://purl.bdrc.io/resource/P705
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    35795441742e47aca89b03ad120e23dd:
      title: པོད ༡་གནས་ལུགས་རང་བྱུང་གི་རྒྱུད་རྡོ་རྗེའི་སྙིང་པོ
      volume_number: 1
      base_file: UT27500_5044_0000.txt
      reference: http://purl.bdrc.io/resource/VLBF273CF2C9F67746
      image_group: '5044'
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/MW27500
  - http://purl.bdrc.io/resource/W27500
  ocr_software: Namsel
created_at: '2021-12-22T11:10:49.118697'
last_modified_at: '2021-12-22T11:10:49.118704'
statistics:
  total_words: 111851
  total_non_words: 14294
quality:
  non_words_ratio: 0.13
